on: [push]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Codiga Code Quality Check
    steps:
    - name: Check code meets quality standards
      id: codiga
      uses: codiga/github-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        codiga_api_token: ${{ secrets.CODIGA_API_TOKEN }}
        force_ref: 'none'
        min_quality_grade: 'GOOD'
        min_quality_score: '90'
        max_defects_rate: '0.001'
        max_complex_functions_rate: '0.5'
        max_long_functions_rate: '0.4'
        project_name: ''
        max_timeout_sec: '600'